server:
  port: 8085
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: vouchers
  application:
    name: VOUCHER-REQUEST
  mail:
    host: smtp.gmail.com
    port: 587
    username: tulasirao2001@gmail.com
    password: bdxu pkwd yboz lhna
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
 
