name: Java CI with CodeGuru Reviewer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build and Package Maven for user-service
        working-directory: ${{ github.workspace }}/user-service
        run: mvn clean package

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          build_path: .
          s3_bucket: codeguru-reviewer-glp-s3-2

      - name: List Files in Build Directory
        run: ls -al ${{ github.workspace }}/user-service

      - name: Upload review result
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codeguru-results.sarif.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
